# Form implementation generated from reading ui file 'Excel2Proto.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ConverterProto(object):
    def setupUi(self, ConverterProto):
        ConverterProto.setObjectName("ConverterProto")
        ConverterProto.resize(802, 520)
        self.scrollArea_files = QtWidgets.QScrollArea(parent=ConverterProto)
        self.scrollArea_files.setGeometry(QtCore.QRect(0, 0, 800, 320))
        self.scrollArea_files.setWidgetResizable(True)
        self.scrollArea_files.setObjectName("scrollArea_files")
        self.scrollArea_file = QtWidgets.QWidget()
        self.scrollArea_file.setGeometry(QtCore.QRect(0, 0, 798, 318))
        self.scrollArea_file.setObjectName("scrollArea_file")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.scrollArea_file)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 801, 321))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.vLayout_files = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.vLayout_files.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.vLayout_files.setContentsMargins(0, 0, 0, 0)
        self.vLayout_files.setObjectName("vLayout_files")
        self.checkBox = QtWidgets.QCheckBox(parent=self.verticalLayoutWidget)
        self.checkBox.setObjectName("checkBox")
        self.vLayout_files.addWidget(self.checkBox)
        self.scrollArea_files.setWidget(self.scrollArea_file)
        self.scrollArea_logs = QtWidgets.QScrollArea(parent=ConverterProto)
        self.scrollArea_logs.setGeometry(QtCore.QRect(0, 359, 800, 161))
        self.scrollArea_logs.setWidgetResizable(True)
        self.scrollArea_logs.setObjectName("scrollArea_logs")
        self.scrollArea_log = QtWidgets.QWidget()
        self.scrollArea_log.setGeometry(QtCore.QRect(0, 0, 798, 159))
        self.scrollArea_log.setObjectName("scrollArea_log")
        self.textEdit = QtWidgets.QTextEdit(parent=self.scrollArea_log)
        self.textEdit.setGeometry(QtCore.QRect(0, 0, 801, 161))
        self.textEdit.setObjectName("textEdit")
        self.scrollArea_logs.setWidget(self.scrollArea_log)
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=ConverterProto)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 320, 801, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Button_ChangeDir = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Button_ChangeDir.setFont(font)
        self.Button_ChangeDir.setObjectName("Button_ChangeDir")
        self.horizontalLayout.addWidget(self.Button_ChangeDir)
        self.Button_Refresh = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Button_Refresh.setFont(font)
        self.Button_Refresh.setObjectName("Button_Refresh")
        self.horizontalLayout.addWidget(self.Button_Refresh)
        self.Button_ChangeSecect = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Button_ChangeSecect.setFont(font)
        self.Button_ChangeSecect.setObjectName("Button_ChangeSecect")
        self.horizontalLayout.addWidget(self.Button_ChangeSecect)
        self.Button_ChangeAll = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Button_ChangeAll.setFont(font)
        self.Button_ChangeAll.setObjectName("Button_ChangeAll")
        self.horizontalLayout.addWidget(self.Button_ChangeAll)

        self.retranslateUi(ConverterProto)
        QtCore.QMetaObject.connectSlotsByName(ConverterProto)
        ConverterProto.setTabOrder(self.Button_ChangeSecect, self.Button_ChangeAll)
        ConverterProto.setTabOrder(self.Button_ChangeAll, self.scrollArea_files)
        ConverterProto.setTabOrder(self.scrollArea_files, self.scrollArea_logs)
        ConverterProto.setTabOrder(self.scrollArea_logs, self.Button_Refresh)
        ConverterProto.setTabOrder(self.Button_Refresh, self.Button_ChangeDir)
        ConverterProto.setTabOrder(self.Button_ChangeDir, self.textEdit)
        ConverterProto.setTabOrder(self.textEdit, self.checkBox)

    def retranslateUi(self, ConverterProto):
        _translate = QtCore.QCoreApplication.translate
        ConverterProto.setWindowTitle(_translate("ConverterProto", "Excel Convert protobuf"))
        self.checkBox.setText(_translate("ConverterProto", "CheckBox"))
        self.Button_ChangeDir.setText(_translate("ConverterProto", "重选路径"))
        self.Button_Refresh.setText(_translate("ConverterProto", "刷新"))
        self.Button_ChangeSecect.setText(_translate("ConverterProto", "转换选中"))
        self.Button_ChangeAll.setText(_translate("ConverterProto", "转换所有"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ConverterProto = QtWidgets.QWidget()
    ui = Ui_ConverterProto()
    ui.setupUi(ConverterProto)
    ConverterProto.show()
    sys.exit(app.exec())
